site_name: TekUp AI Assistant
site_description: Local AI Assistant for automating daily business tasks
site_author: TekUp Team
site_url: https://github.com/JonasAbde/tekup-ai-assistant

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

nav:
  - Home: index.md
  - Getting Started:
    - Installation: docs/SETUP.md
    - Architecture: docs/ARCHITECTURE.md
  - Documentation:
    - Daily Workflows: docs/WORKFLOWS.md
    - Troubleshooting: docs/TROUBLESHOOTING.md
  - API Reference:
    - Billy.dk API: docs/api/tekup-billy-api.md
  - Guides:
    - Daily Workflow Guide: docs/guides/daily-workflow.md
  - Examples:
    - Invoice Creation: examples/create-invoice.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - tables
  - admonition
  - toc:
      permalink: true
      toc_depth: "1-3"

repo_url: https://github.com/JonasAbde/tekup-ai-assistant
repo_name: tekup-ai-assistant
edit_uri: edit/master/
